#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-present Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

export PATH=/opt/bin:/opt/sbin:$PATH

[ ! -d /storage/.opt ] && mkdir -p /storage/.opt

if [ ! -f /opt/bin/opkg ]; then
  wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | /bin/sh
  sed -i '3i. /opt/etc/profile' /opt/etc/init.d/rc.unslung
  echo ""
  read -p "Would you like to reboot now to finish installation (recommended) [y/N]? " choice
  case "$choice" in
    [yY]*)
      reboot
      ;;
  esac
else
  echo "Entware is already installed."
  exit 0
fi
